StartingBoards.add_board :eye_of_the_storm, {
  "starting board name" => "eye_of_the_storm",
  "height" => 11,
  "width" => 10,
  "walls" => [{"posx" => "3","posy" => "3"},{"posx" => "4","posy" => "3"},{"posx" => "5","posy" => "3"},{"posx" => "6","posy" => "3"},{"posx" => "2","posy" => "4"},{"posx" => "7","posy" => "4"},{"posx" => "2","posy" => "6"},{"posx" => "7","posy" => "6"},{"posx" => "3","posy" => "7"},{"posx" => "4","posy" => "7"},{"posx" => "5","posy" => "7"},{"posx" => "6","posy" => "7"}],
  "upgradeSquares" => [{"posx" => "4","posy" => "5"},{"posx" => "5","posy" => "5"}],
  "boardStack" => [[{"posx" => "1","posy" => "0","type" => "rook","side" => "white"},{"posx" => "2","posy" => "0","type" => "knight","side" => "white"},{"posx" => "3","posy" => "0","type" => "bishop","side" => "white"},{"posx" => "4","posy" => "0","type" => "queen","side" => "white"},{"posx" => "5","posy" => "0","type" => "king","side" => "white"},{"posx" => "6","posy" => "0","type" => "bishop","side" => "white"},{"posx" => "7","posy" => "0","type" => "knight","side" => "white"},{"posx" => "8","posy" => "0","type" => "rook","side" => "white"},{"posx" => "1","posy" => "1","type" => "pawn","side" => "white"},{"posx" => "2","posy" => "1","type" => "pawn","side" => "white"},{"posx" => "3","posy" => "1","type" => "pawn","side" => "white"},{"posx" => "4","posy" => "1","type" => "pawn","side" => "white"},{"posx" => "5","posy" => "1","type" => "pawn","side" => "white"},{"posx" => "6","posy" => "1","type" => "pawn","side" => "white"},{"posx" => "7","posy" => "1","type" => "pawn","side" => "white"},{"posx" => "8","posy" => "1","type" => "pawn","side" => "white"},{"posx" => "1","posy" => "9","type" => "pawn","side" => "black"},{"posx" => "2","posy" => "9","type" => "pawn","side" => "black"},{"posx" => "3","posy" => "9","type" => "pawn","side" => "black"},{"posx" => "4","posy" => "9","type" => "pawn","side" => "black"},{"posx" => "5","posy" => "9","type" => "pawn","side" => "black"},{"posx" => "6","posy" => "9","type" => "pawn","side" => "black"},{"posx" => "7","posy" => "9","type" => "pawn","side" => "black"},{"posx" => "8","posy" => "9","type" => "pawn","side" => "black"},{"posx" => "1","posy" => "10","type" => "rook","side" => "black"},{"posx" => "2","posy" => "10","type" => "knight","side" => "black"},{"posx" => "3","posy" => "10","type" => "bishop","side" => "black"},{"posx" => "4","posy" => "10","type" => "queen","side" => "black"},{"posx" => "5","posy" => "10","type" => "king","side" => "black"},{"posx" => "6","posy" => "10","type" => "bishop","side" => "black"},{"posx" => "7","posy" => "10","type" => "knight","side" => "black"},{"posx" => "8","posy" => "10","type" => "rook","side" => "black"}]],
  "turn" => "white",
  "playerSides" =>  {
    "white" => "unassigned",
    "black" => "unassigned"
  }
}
