default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres_user
  password: postgres_password
  host: xchess-postgres  # <-- Use the Postgres service name here

development:
  <<: *default
  database: chess_app_development

test:
  <<: *default
  database: chess_app_test

production:
  <<: *default
  database: chess_app_production
  username: chess_app
  password: <%= ENV['CHESS_APP_DATABASE_PASSWORD'] %>
